# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24fb25a7f98913bffbc44f15b0cd12ce0a50c6d2a4f75eb21b07e76216c866bb3a29f30228cd3d17f5aa0d789087e172cff8cd8074bd8523396dd1a0ce2a2d31

test:
  secret_key_base: 6cfd329864cc0f2ee5975de4c28d0105c39dd60b758f1bd117507c77686076e45ff17ac233f22fa53beedcb9c87d5cec6a039db65fbdfc378741fe5319d9601b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
